name: mlflow-env
channels:
  - conda-forge
dependencies:
  - pip == 23.2.1
  - Python == 3.11.5
  - pip:
      - python-docx == 1.0.1
      - Document == 1.0
      - langchain == 0.0.286
      - openai == 0.28.0
      - python-magic == 0.4.27
      - PyMuPDF == 1.23.5
      - pypdf2 == 2.11.1
      - PyYAML == 6.0.1
      - mlflow>=1.0
      - prefect
